src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: '`order`')]
class Order
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $User = null;

    #[ORM\Column]
    private array $Products = [];

    #[ORM\Column]
    private ?float $TotalPrice = null;

    #[ORM\Column]
    private ?float $Discount = null;

    #[ORM\Column]
    private ?float $Price = null;

    #[ORM\Column(length: 255)]
    private ?string $Status = null;

    #[ORM\Column(length: 255)]
    private ?string $Address = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getProducts(): array
    {
        return $this->Products;
    }

    public function setProducts(array $Products): self
    {
        $this->Products = $Products;

        return $this;
    }

    public function getTotalPrice(): ?float
    {
        return $this->TotalPrice;
    }

    public function setTotalPrice(float $TotalPrice): self
    {
        $this->TotalPrice = $TotalPrice;

        return $this;
    }

    public function getDiscount(): ?float
    {
        return $this->Discount;
    }

    public function setDiscount(float $Discount): self
    {
        $this->Discount = $Discount;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->Price;
    }

    public function setPrice(float $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->Status;
    }

    public function setStatus(string $Status): self
    {
        $this->Status = $Status;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->Address;
    }

    public function setAddress(string $Address): self
    {
        $this->Address = $Address;

        return $this;
    }
}

templates/home_controller/index.html.twig
{% extends 'template.html.twig' %}

{% block content %}
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="">Homepage</h1>
  </div>

  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="{{ path('home') }}">All Products</a>
      </li>
      {% set path = '' %}
      {% for cat in categoriesArray %}
        {% set path = path ~ '/' ~ cat %}
        {% if loop.last %}
          <li class="breadcrumb-item active" aria-current="page">{{ cat }}</li>
        {% else %}
          <li class="breadcrumb-item">
            <a href="{{ path('home', { slug: path|trim('/', 'left') }) }}">{{ cat }}</a>
          </li>
        {% endif %}
      {% endfor %}
    </ol>
  </nav>

  {% if (categories|length) > 0 %}
    <div class="d-flex align-items-center mb-4" style="gap: 15px;">
      <h3>Categories</h3>
      <button id="left-button" class="btn btn-info text-white"><span data-feather="chevron-left" class="align-text-bottom"></span></button>
      <button id="right-button" class="btn btn-info text-white"><span data-feather="chevron-right" class="align-text-bottom"></span></button>
    </div>

    <div id="categories" class="row flex-row flex-nowrap mb-4" style="gap:15px; overflow-x: scroll;">
      {% for cat in categories %}
        <div class="card" style="width: 18rem;">
          <a href="{{ (app.request.uri|trim('/', 'right')) ~ '/' ~ cat.slug }}" class="text-decoration-none">
            <div class="card-body">
              <h5 class="card-title">{{ cat.name }}</h5>
              <h6 class="card-subtitle mb-2 text-muted">{{ cat.slug }}</h6>
              <span data-feather="arrow-right" class="align-text-bottom"></span>
            </div>
          </a>
        </div>
      {% endfor %}
    </div>
  {% endif %}

  {% if (products|length) > 0 %}
    <hr />
    <h3 class="mb-4">Products</h3>

    <div class="row flex-row mb-4" style="gap: 15px;">
      {% for product in products %}
        <div class="card" style="width: 18rem;">
          <a href="javascript:void(0);" class="text-decoration-none productCard" data-product="{{ product.id }}" data-name="{{ product.name }}" data-price="{{ product.price }}">
            <div class="card-body">
              <p>
                <span data-feather="shopping-cart" class="align-text-bottom"></span>
                $ {{ product.price }}
              </p>
              <h5 class="card-title">{{ product.name }}</h5>
              <small class="mb-2 text-muted">{{ product.getCategory|join(', ') }}</small>
            </div>
          </a>
        </div>
      {% endfor %}
    </div>
  {% endif %}
{% endblock %}

{% block javascript %}
  <script>
    jQuery(document).ready(function ($) {
      $('#right-button').click(function () {
        event.preventDefault()
        $('#categories').animate(
          {
            scrollLeft: '+=900px'
          },
          'slow'
        )
      })
    
      $('#left-button').click(function () {
        event.preventDefault()
        $('#categories').animate(
          {
            scrollLeft: '-=900px'
          },
          'slow'
        )
      })
    
      $('.productCard').click(function () {
        {% if app.user %}
          const product = $(this).data('product')
          const name = $(this).data('name')
          const price = $(this).data('price')
          const quantity = prompt(`How many "${name}" will you add to your shopping cart?`, 0)
      
          if (isNaN(quantity)) {
            alert('You can only enter numeric characters.')
          }
      
          if (quantity > 0) {
            $.ajax({
              type: 'POST',
              url: '{{ path("app_shopping_cart_add") }}',
              data: {
                product,
                quantity,
                price
              },
              success: function (response) {
                toastr.success('The product has been successfully added to your shopping cart!')
              }
            })
          }
        {% else %}
          toastr.warning('You must sign in first.')
        {% endif %}
      })
    })
  </script>
{% endblock %}